### ISSUE TITLE
Bulk file decryption

### ISSUE THREAD

**Issue by Aceclark** [pgptool/pgptool#177] opened 2019-01-28 07:54 UTC
I had accidentally decrypted alot of files. I am not used to PGP that well and I guess I was playing around trying to figure it out.  So anyways, I need to decrypt alot of files, but can't find a way to do that.  Anything is better than doing this one at a time.

Thanks everyone!

**Comment by skarpushin** [comment] 2019-01-28 10:11
@Aceclark this feature is planned -- #9 .
Can you provide an example user actions and expectations how exactly you see it's happening?

I.e. 
1. Click Menu -> Decrypt multiple
2. "Decrypt multiple" window opens
3. ... what's next?

**Comment by timetoseek** [comment] 2020-04-26 00:52
Thank you Sergey for creating an outstanding tool, just discovered today and testing it out.  
A huge improvement would be the ability to encrypt/decrypt **multiple files** or **folders/subfolders**. 
For example, tax documents, bank statements, etc, for an entire year are stored in a single folder. 
Entire folder encryption/decryption would be much faster than trying to encrypt/decrypt several dozen files one-by-one, would take a very long time.

**Comment by skarpushin** [comment] 2020-04-26 11:41
@timetoseek thanks for the feedback! I totally understand the background for this feature request, because I need this feature as well and for the same reason :-)
But this tool is a totally hobby project and is not a source of income, hence I cannot predict when this feature will be implemented. But it is for sure on the backlog and will be implemented some day, that's for sure.

**Comment by skarpushin** [comment] 2020-04-26 11:42
p.s. I'm closing this feature request as there is no answer from @Aceclark and this is a duplicate of #9

**Closed by skarpushin** 2020-04-26 11:42 UTC
Labels: feature request
