### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by buzzsaw89** [pgptool/pgptool#269] opened 2022-07-07 14:14 UTC
I'm getting an error message when I try and decrypt more than one message. 

I have to close down the tool and reopen it to decrypt. 

I'm running Windows 10.

![PGPToolError Message](https://user-images.githubusercontent.com/108882274/177794416-5bbae2ef-2ce9-41c1-bbc5-377e3034a819.jpg)

**Comment by skarpushin** [comment] 2022-07-07 16:05
@buzzsaw89 could you please share a log file with me via email? Before sending it please review it to make sure that you do not expose any sensitive information.
My email: sergey.v.karpushin@gmail.com
Log location: `c:\Users\USER\pgptool-gui.log` (make sure to replace `USER` with your user name

**Comment by skarpushin** [comment] 2023-02-09 15:04
I guess this one fell through the cracks, I cannot find any relevant emails. So I'm closing this one. 
p.s. this seem to be a duplicate of https://github.com/pgptool/pgptool/issues/244

**Closed by skarpushin** 2023-02-09 15:04 UTC
Labels: Fix
