### ISSUE TITLE
Fix: Password prompt is not appearing when running on Microsoft Surface Pro 3

### ISSUE THREAD

**Issue by dpesloid** [pgptool/pgptool#260] opened 2021-11-22 21:22 UTC
I used PGP tool for years now.   I had to install on my surface.   When I decrypt a PGP file the program never give me  the screen to enter key to decrypt.

Thanks

**Comment by skarpushin** [comment] 2021-11-23 06:17
hi @dpesloid 
I'm glad it worked for you throughout the years. And I'm sorry you ran into troubles on surface. 
I don't have such device at hand, so I cannot reproduce this issue myself. 
Can you please provide following information:

- Link to exact model that you use?
- Please also confirm operation system version
- Any screenshots that confirm the issue (feel free to blur our parts that you're not comfortable sharing)?

?

**Comment by dpesloid** [comment] 2021-11-23 13:48
Thanks for the response

I have a Surface Pro 3
Micrsoft Windows Pro 10

I got the file to decrpyt .   If i double click on the file, PGP tool never gives me the option to enter key.   If I right click on file and select decrypt with verify, I get my file.

Thanks

**Comment by skarpushin** [comment] 2021-11-23 16:06
@dpesloid thank you for clarification. I'd need additional information so that I can narrow down the issues and hopefully nail it down to the root cause:

1. After  double-clicking on a file -- have you tried to get to opened windows list (similar to Alt+Tab in regular mode)? Did you see password prompt there?
2. "If I right click on file and select **decrypt with verify**" - which application is handling this menu item? Is it some kind of native windows application, or is it some other application?
3. Are you running your surface in "Tablet" mode on or off? Is behavior the same in both modes?
4. Have you tried to open PGP Tool application and initiate decryption from application itself instead of a file browser?

**Comment by dpesloid** [comment] 2021-11-23 16:23
1. After double-clicking on a file -- have you tried to get to opened windows list (similar to Alt+Tab in regular mode)? Did you see password prompt there?   I alt tab and check no password prompt
2. "If I right click on file and select decrypt with verify" - which application is handling this menu item? Is it some kind of native windows application, or is it some other application?  My mistake,  a different program did the decrypting.
3. Are you running your surface in "Tablet" mode on or off? Is behavior the same in both modes?  Tablet Mode is off
4. Have you tried to open PGP Tool application and initiate decryption from application itself instead of a file browser?  Same results as using windows explorer to select my file
5.

**Comment by dpesloid** [comment] 2021-12-01 16:38
Is there any fix for this issue? I tried today and still never get the prompt to enter decryption key

**Comment by skarpushin** [comment] 2021-12-02 20:02
@dpesloid not yet, I cannot reproduce it. I'll need to get my hands on Surface 3 in order to get some progress on this issue. On my laptops with Windows 10 issue is not reproducible, so I'm guessing it is specific to windows 10 tablets. 

Having said that, I apologize, but I cannot give you any ETA as to when you can expect the fix. 

p.s. as a "hail mary" maybe you can share file `pgptool-gui.log` that is located in your user home folder? Please share it privately via my email `sergey.v.karpushin@gmail.com`. Also feel free to review it before sharing and replacing any file names or key names if you feel like it. Honestly, I doubt that it will allow me to spot any issues, but if you find word "Exception" there, then this information could be useful for troubleshooting.

**Comment by skarpushin** [comment] 2021-12-03 05:11
@dpesloid thank you for sharing log file. The exceptions mentioned in it are not relevant. But I found this:

```
2021-12-02 14:07:58.843 DEBUG main EntryPoint Processing postponed args from secondary instance: [path\file.txt]
2021-12-02 14:07:58.844 INFO  main Usage {"p":{"c":"CommandLineArgs","i":{"args":["path\file.txt"]}}}
2021-12-02 14:07:58.876 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptionWindowOpener","action":"action.encrypt"}}}
2021-12-02 14:07:58.877 DEBUG AWT-EventQueue-0 EncryptOnePm$4 Source changed to : path\file.txt
==> 2021-12-02 14:07:58.886 DEBUG AWT-EventQueue-0 UiUtils Positioning window according to multi-monitor configuration: 0: x=0,y=0,w=1440,h=960, 1: x=2160,y=0,w=1280,h=1024
2021-12-02 14:07:58.887 DEBUG AWT-EventQueue-0 UiUtils determineGraphicsDeviceByWindow x=382,y=305,w=676,h=351
2021-12-02 14:07:58.887 DEBUG AWT-EventQueue-0 UiUtils - Checking GraphicsDevice: 0: x=0,y=0,w=1440,h=960
2021-12-02 14:07:58.887 DEBUG AWT-EventQueue-0 UiUtils   - Checking GraphicsConfiguration: x=0,y=0,w=1440,h=960
2021-12-02 14:07:58.888 DEBUG AWT-EventQueue-0 UiUtils - Checking GraphicsDevice: 1: x=2160,y=0,w=1280,h=1024
2021-12-02 14:07:58.888 DEBUG AWT-EventQueue-0 UiUtils   - Checking GraphicsConfiguration: x=2160,y=0,w=1280,h=1024
2021-12-02 14:07:58.888 DEBUG AWT-EventQueue-0 UiUtils Parent window x=382,y=305,w=676,h=351 belongs to screen 0: x=0,y=0,w=1440,h=960
==> 2021-12-02 14:08:00.379 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:01.637 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:03.619 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:04.787 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:05.411 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:05.963 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:06.443 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:07.948 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"MainFramePm","action":"action.exit"}}}
2021-12-02 14:08:07.959 INFO  AWT-EventQueue-0 Usage {"p":{"c":"ApplicationExit","i":{}}}
```

It tells me that application detects 2 monitors. Are you using some kind of external monitor? It is possible that application is getting displayed on that other monitor. But on other hand, it looks like it was the case from day 1 of usage on this device, and you was able to import key and perform encryption. I'm puzzled here tbh.

Is it possible to switch to single monitor configuration?

Also, in logs I see that you've tried to encrypt some text files, but in your first message you share that issue is happening with decryption. Please confirm which window is not appearing encryption or decryption, or both? 

And, what happens if you just move main window aside and check if "lost" window is underneath? Because from logs I see that there were 7 encryption windows opened

**Comment by dpesloid** [comment] 2021-12-03 12:31
I am using 2 monitors.  I will check again for missing screens


On Dec 3, 2021, at 12:12 AM, Sergey Karpushin ***@***.***> wrote:

﻿

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@dpesloid<https://scanmail.trustwave.com/?c=4062&d=m6ep4S2sA-8vK_796HF6207D8nBKQCh4UZ_DK0LngQ&s=1739&u=https%3a%2f%2fgithub%2ecom%2fdpesloid> thank you for sharing log file. The exceptions mentioned in it are not relevant. But I found this:

2021-12-02 14:07:58.843 DEBUG main EntryPoint Processing postponed args from secondary instance: [path\file.txt]
2021-12-02 14:07:58.844 INFO  main Usage {"p":{"c":"CommandLineArgs","i":{"args":["path\file.txt"]}}}
2021-12-02 14:07:58.876 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptionWindowOpener","action":"action.encrypt"}}}
2021-12-02 14:07:58.877 DEBUG AWT-EventQueue-0 EncryptOnePm$4 Source changed to : path\file.txt
==> 2021-12-02 14:07:58.886 DEBUG AWT-EventQueue-0 UiUtils Positioning window according to multi-monitor configuration: 0: x=0,y=0,w=1440,h=960, 1: x=2160,y=0,w=1280,h=1024
2021-12-02 14:07:58.887 DEBUG AWT-EventQueue-0 UiUtils determineGraphicsDeviceByWindow x=382,y=305,w=676,h=351
2021-12-02 14:07:58.887 DEBUG AWT-EventQueue-0 UiUtils - Checking GraphicsDevice: 0: x=0,y=0,w=1440,h=960
2021-12-02 14:07:58.887 DEBUG AWT-EventQueue-0 UiUtils   - Checking GraphicsConfiguration: x=0,y=0,w=1440,h=960
2021-12-02 14:07:58.888 DEBUG AWT-EventQueue-0 UiUtils - Checking GraphicsDevice: 1: x=2160,y=0,w=1280,h=1024
2021-12-02 14:07:58.888 DEBUG AWT-EventQueue-0 UiUtils   - Checking GraphicsConfiguration: x=2160,y=0,w=1280,h=1024
2021-12-02 14:07:58.888 DEBUG AWT-EventQueue-0 UiUtils Parent window x=382,y=305,w=676,h=351 belongs to screen 0: x=0,y=0,w=1440,h=960
==> 2021-12-02 14:08:00.379 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:01.637 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:03.619 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:04.787 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:05.411 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:05.963 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:06.443 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"EncryptOnePm","action":"action.cancel"}}}
2021-12-02 14:08:07.948 INFO  AWT-EventQueue-0 Usage {"p":{"c":"Action","i":{"ctx":"MainFramePm","action":"action.exit"}}}
2021-12-02 14:08:07.959 INFO  AWT-EventQueue-0 Usage {"p":{"c":"ApplicationExit","i":{}}}


It tells me that application detects 2 monitors. Are you using some kind of external monitor? It is possible that application is getting displayed on that other monitor. But on other hand, it looks like it was the case from day 1 of usage on this device, and you was able to import key and perform encryption. I'm puzzled here tbh.

Is it possible to switch to single monitor configuration?

Also, in logs I see that you've tried to encrypt some text files, but in your first message you share that issue is happening with decryption. Please confirm which window is not appearing encryption or decryption, or both?

And, what happens if you just move main window aside and check if "lost" window is underneath? Because from logs I see that there were 7 encryption windows opened

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://scanmail.trustwave.com/?c=4062&d=m6ep4S2sA-8vK_796HF6207D8nBKQCh4UcnIeUPj1Q&s=1739&u=https%3a%2f%2fgithub%2ecom%2fpgptool%2fpgptool%2fissues%2f260%23issuecomment-985222254>, or unsubscribe<https://scanmail.trustwave.com/?c=4062&d=m6ep4S2sA-8vK_796HF6207D8nBKQCh4UZyTJBW3hA&s=1739&u=https%3a%2f%2fgithub%2ecom%2fnotifications%2funsubscribe-auth%2fAWTZ65T2VLXS3ZA35DX26K3UPBGRVANCNFSM5IR7XH4Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://scanmail.trustwave.com/?c=4062&d=m6ep4S2sA-8vK_796HF6207D8nBKQCh4UZHFe0ewhw&s=1739&u=https%3a%2f%2fapps%2eapple%2ecom%2fapp%2fapple-store%2fid1477376905%3fct%3dnotification-email%26mt%3d8%26pt%3d524675> or Android<https://scanmail.trustwave.com/?c=4062&d=m6ep4S2sA-8vK_796HF6207D8nBKQCh4UZvGfxO71w&s=1739&u=https%3a%2f%2fplay%2egoogle%2ecom%2fstore%2fapps%2fdetails%3fid%3dcom%2egithub%2eandroid%26referrer%3dutm%5fcampaign%253Dnotification-email%2526utm%5fmedium%253Demail%2526utm%5fsource%253Dgithub>.

________________________________
This e-mail message has been scanned by SEG Cloud
________________________________

##################################################################################
Attention: 
This message and any attachments are confidential and intended solely for the addressees. 
If you receive this message in error, please delete it and immediately notify the sender. Any views or opinions expressed in this message are those of the individual(s) and not necessarily of the organization. No reliance may be placed on this message without written confirmation from an authorized representative of its contents. If the reader of this message is not the intended recipient, you are hereby notified that any unauthorized use, copying or dissemination is prohibited. E-mails are susceptible to alteration. Neither Marketing Systems Group nor any of its subsidiaries or affiliates shall be liable for the message if altered, changed or falsified.

Scanned by SEG Cloud
##################################################################################

**Comment by dpesloid** [comment] 2021-12-03 13:36
***@***.***

I checked both monitors.  No screen to enter decryption key.   I use both monitors all day, so turning off 2 monitors will be a real pain in the neck to do to use pgp.  Any other thoughts?

**Comment by skarpushin** [comment] 2021-12-04 06:13
@dpesloid can please try to switch to 1 monitor just temporarily to see if issue is resolved by that? That will help to narrow down the root cause.

**Comment by dpesloid** [comment] 2021-12-06 13:57
Hi,

I switched to 1 monitor and get the same results.   Never get the prompt to enter key to decrypt

**Comment by skarpushin** [comment] 2021-12-08 06:06
@dpesloid I have no idea what is going wrong :-(

Are you open to an idea of having quick online session where you can share your screen and reproduce the issue? This should take 10 to 15 minutes.

**Comment by dpesloid** [comment] 2021-12-08 14:19
Hi Sergey,

Would teams work for you?    I am in the Eastern Time Zone.   Any time after 10:30 AM works for me.

Thanks
David

**Comment by skarpushin** [comment] 2021-12-14 03:38
@dpesloid I'm not using Teams, so I cannot send you an invite. Please send me a calendar invite for today 10:30 AM EST. Your timezone is same as Boston and New York, right?

**Comment by dpesloid** [comment] 2021-12-14 03:39
Correct

On Dec 13, 2021, at 10:39 PM, Sergey Karpushin ***@***.***> wrote:

﻿

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@dpesloid<https://scanmail.trustwave.com/?c=4062&d=2ZG44UyeP2uB1V-ZlNtHetjbjs0D7aPr5N-qlANXNw&s=1739&u=https%3a%2f%2fgithub%2ecom%2fdpesloid> I'm not using Teams, so I cannot send you an invite. Please send me a calendar invite for today 10:30 AM EST. Your timezone is same as Boston and New York, right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://scanmail.trustwave.com/?c=4062&d=2ZG44UyeP2uB1V-ZlNtHetjbjs0D7aPr5N2hxAYLNg&s=1739&u=https%3a%2f%2fgithub%2ecom%2fpgptool%2fpgptool%2fissues%2f260%23issuecomment-993127096>, or unsubscribe<https://scanmail.trustwave.com/?c=4062&d=2ZG44UyeP2uB1V-ZlNtHetjbjs0D7aPr5NmokVcLYQ&s=1739&u=https%3a%2f%2fgithub%2ecom%2fnotifications%2funsubscribe-auth%2fAWTZ65T3GKFVVZLJBYDKSPTUQ235RANCNFSM5IR7XH4Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://scanmail.trustwave.com/?c=4062&d=2ZG44UyeP2uB1V-ZlNtHetjbjs0D7aPr5NGsxAYAMQ&s=1739&u=https%3a%2f%2fapps%2eapple%2ecom%2fapp%2fapple-store%2fid1477376905%3fct%3dnotification-email%26mt%3d8%26pt%3d524675> or Android<https://scanmail.trustwave.com/?c=4062&d=2ZG44UyeP2uB1V-ZlNtHetjbjs0D7aPr5NuvwFILYQ&s=1739&u=https%3a%2f%2fplay%2egoogle%2ecom%2fstore%2fapps%2fdetails%3fid%3dcom%2egithub%2eandroid%26referrer%3dutm%5fcampaign%253Dnotification-email%2526utm%5fmedium%253Demail%2526utm%5fsource%253Dgithub>.

________________________________
This e-mail message has been scanned by SEG Cloud
________________________________

##################################################################################
Attention: 
This message and any attachments are confidential and intended solely for the addressees. 
If you receive this message in error, please delete it and immediately notify the sender. Any views or opinions expressed in this message are those of the individual(s) and not necessarily of the organization. No reliance may be placed on this message without written confirmation from an authorized representative of its contents. If the reader of this message is not the intended recipient, you are hereby notified that any unauthorized use, copying or dissemination is prohibited. E-mails are susceptible to alteration. Neither Marketing Systems Group nor any of its subsidiaries or affiliates shall be liable for the message if altered, changed or falsified.

Scanned by SEG Cloud
##################################################################################

**Comment by skarpushin** [comment] 2023-04-19 07:49
I do not have means to troubleshoot this and also there were no similar reports. Closing.

**Closed by skarpushin** 2023-04-19 07:49 UTC
Labels: Fix
