### ISSUE TITLE
Feature Request: Import several keys from a file

### ISSUE THREAD

**Issue by Boran** [pgptool/pgptool#160] opened 2018-08-26 06:17 UTC
I have a file containing a list of public keys and share this between a group of users. This is an easy keys to sync a key list between users.
When this file is imported with pgptool, only the first key is seen and imported.

Several pgp tools historically allow this so it is probably a quasi standard?

Note: this is not the same as another issue list here requesting to open several key files at a time, or reading a public and private key from the same file.

Thanks in advance for considering this.

**Comment by skarpushin** [comment] 2018-08-27 01:51
@Boran , thanks for the feedback. Are you certain it's not a duplicate of #156 ?

**Comment by Boran** [comment] 2018-08-27 05:44
Yes the general issue is similar but the aim I understood there is to import a secret key in afile containing both public and secret..   "it only imports the public key, the secret key is ignored."

What I'm suggesting is that one can have one file with several public keys, that can be imported at once.

**Comment by skarpushin** [comment] 2018-08-27 12:41
Oh, right, I missed that. Essentially both issues will share pretty much same implementation. 
I'll add this feature to the next release.

**Comment by Boran** [comment] 2019-01-27 16:20
Great, appreciated!
I have tested:
1. importing from several files (clicking on several files in one operation): works fine
2. however, when importing a file containing several PKs, only the first key was recognised.
(Note: feature "2" is no longer important important for me, now that "1", is implement :-).

**Comment by Boran** [comment] 2019-01-28 20:20
As stated at the top of this thread:
"I have a text file containing a list of public keys and share this between a group of users. .... When this file is imported with pgptool, only the first key is seen and imported."

thanks for your interest.

**Comment by Boran** [comment] 2019-02-03 07:19
Above I have 0.5.3, now 0.5.4.
a) Open file to be imported in notedpad, and select the contents. Then Key Ring > Import PGP Key from clipboard. This works, three keys are shown.
b) Key Ring > Import PGP Key > select the file with the list. Only the first key is shown in the list.

The file looks like:
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: PGP Desktop 10.1.1 (Build 10) - not licensed for commercial use: www.pgp.com

XXXXX
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: PGP 8.1 - not licensed for commercial use: www.pgp.com

YYYYY
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: PGP 8.1 - not licensed for commercial use: www.pgp.com

ZZZZ
-----END PGP PUBLIC KEY BLOCK-----

**Comment by skarpushin** [comment] 2019-09-22 19:35
@Boran , finally got some time to look into this. Unfortunately, was unable to reproduce the issue. 
Below is the exact file contents that I've used in this attempt. 
I know it has been a long time since you filed this request, so you probably don't care about this anymore. 
If you can provide me with an example which will help to reproduce the issue - I would really appreciate it. 
For now I'm closing this request. I'll reopen this in case I got a feedback from you. 
BTW: Note that if 2 out of 3 keys were already imported, then truly only 1 of them will appear in the list of imported keys. 


```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.56

mQGiBFiEYDwRBADRQztFDTN7HxCEqzkVr5QSt1Zn+w0m1Q/GYyRRBupxU1bbMHLy
lzKBGdYyU4G+P4HmhBOmFGeXaqmpIpnfaAijqP9sxjY+pYi4255WouD3it2ECtwz
bev4OytzKgJD2wVuuoNMKVNbdBA1X1Lfivsn9nzD6WLFuL6esa6LSWPqqwCghIj6
iNbncjL9doaajnmOAL7a0gMEAMnrvu9J5IbXLSlgo+wzn9OpOR0QjmqFf+wtT6iH
bB5XIrOxFfYNyEDjIfbh3NGXtAm77y77J++W1hygvyZAfiAU0zUU+y0kpkLhMAAy
KniSYo2rE38N4AE1ziVdwqaZ27X4LxGgwuXOgnDCNf8m6OCrfB+TzsLD12srx9pN
jKMjBAClmYupXP52/wjG760iBJepkT+zt8kWDQ4Ch1Ka5rTroESG+Uo5pg1dYdkq
Cs88N0m3qGrkL1WLKydM1n/DetHZCAUGhbfbERB9YfhV52JNMGBP9227vM0lHvjy
d/KQ9pCsrxb7/xA2P0q62e49JZY+3sFL12Iyd7OADDBSQfzO6LQXQWxpY2UgPGFs
aWNlQGVtYWlsLmNvbT6IXgQTEQIAHgUCWIRgPAoLBwgJBAMGBQIKCBUFAQMCCAkK
AxYBAgAKCRBh7YzhnzFbCSq0AJ9c3aNmmANfVWZbTkzx5ZLzdr0bmACffv6Vhie5
YhDF7NsKvVfR29X0Xlq5AYwEWIRgPBAEAKIU2L711d46EyJN1hSMRO2+02Wde363
Y9twLNCb/DkjHjYHIrY9EyLuwq28jNPJj94Nyq32yQcF//JTuouuYiIIVSn8C3tG
lMSnfN7adHATvvAiBLqOMO0Z3zGMnxqinsUt5TQ+0/y70Hv3FrUEwFbvUxe3VxlN
zm6rkEexbl1LA/49z3FcihaALbDm0E/G1UyTO9LmPhQFPw8eAkW+kRzXUEySxErm
O5CpyNjVziHqjgHO7VIFZs/tL9q/DyBDA3azZ2QSvApQHdKCu1drVGSS6h3zHxi8
4kWFtCOfOyR3e/7xbUdQZax3m2ZfFIgrXDA1tFiS4SXHXzt87G2tx9ficAP8DRyG
rNldwh3FwO4jhEIBEzTo0fmx3WAbwYyx0gVhl1VCOMB+bPgrDTHZhrGMOelB35gC
k3Lt26r8woLiQVYEeFLn6rwJU51dS7wGuTM4MeoztMN57uj3iCtTnNJ6tfnLlmHf
zM+XHKdYhlHGHYlBBi4kzvK5BnJNBweYBZ4W6piIXgQYEQIAHgUCWIRgPAoLBwgJ
BAMGBQIKCBUFAQMCCAkKAxYBAgAKCRBh7YzhnzFbCUL4AJ4oR9L3AaxjjFigej6u
ylRqVPMaqQCfQwa/EpHzfFrps1L1YYJ4TJJuWro=
=Y1/F
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.56

mQGiBFiEaYsRBADRQztFDTN7HxCEqzkVr5QSt1Zn+w0m1Q/GYyRRBupxU1bbMHLy
lzKBGdYyU4G+P4HmhBOmFGeXaqmpIpnfaAijqP9sxjY+pYi4255WouD3it2ECtwz
bev4OytzKgJD2wVuuoNMKVNbdBA1X1Lfivsn9nzD6WLFuL6esa6LSWPqqwCghIj6
iNbncjL9doaajnmOAL7a0gMEAMnrvu9J5IbXLSlgo+wzn9OpOR0QjmqFf+wtT6iH
bB5XIrOxFfYNyEDjIfbh3NGXtAm77y77J++W1hygvyZAfiAU0zUU+y0kpkLhMAAy
KniSYo2rE38N4AE1ziVdwqaZ27X4LxGgwuXOgnDCNf8m6OCrfB+TzsLD12srx9pN
jKMjA/4zmD/SUHPMRixJwQKkLwxDSjBce0BxpTCCxI5NxRl/iAXOEH0YlVJwAb9Z
Putwm8W4ihQyhgYJC/64fBAoX/ZAMwtRlF4Su3W1wV10BUuknRfSnSpE69vxVGXE
xG2tpdEm5mJVnPCCkoUqGeZU8Yf6spCa2z7l0BwVPIyfez+vkLQTQm9iIDxib2JA
ZW1haWwuY29tPoheBBMRAgAeBQJYhGmLCgsHCAkEAwYFAgoIFQUBAwIICQoDFgEC
AAoJEBRcXsmfYJlDtn0An3BhSA6A6aoybjQpzIp4d5XoxVE8AJ9foBCZrNyY60Rp
88nEH2hWHiTGnbkBjARYhGmLEAQAohTYvvXV3joTIk3WFIxE7b7TZZ17frdj23As
0Jv8OSMeNgcitj0TIu7CrbyM08mP3g3KrfbJBwX/8lO6i65iIghVKfwLe0aUxKd8
3tp0cBO+8CIEuo4w7RnfMYyfGqKexS3lND7T/LvQe/cWtQTAVu9TF7dXGU3ObquQ
R7FuXUsD/j3PcVyKFoAtsObQT8bVTJM70uY+FAU/Dx4CRb6RHNdQTJLESuY7kKnI
2NXOIeqOAc7tUgVmz+0v2r8PIEMDdrNnZBK8ClAd0oK7V2tUZJLqHfMfGLziRYW0
I587JHd7/vFtR1BlrHebZl8UiCtcMDW0WJLhJcdfO3zsba3H1+JwBACLNAV+fkm8
mlV0UUsXmYSW5rgasG8eqUSjCVkG2Ktqw5LOXzN/aQrkcqJwPIpEP0NSCajEgFyy
NcmP2PcLHtY4v9vqvS2GNSjZiluL/k2ZUyM1ltbs2RYeyWrVw1MTQNm/hCieH7rg
hBZhp8jlWTBPppJSWXJzgrYXxdMHK0xxfYheBBgRAgAeBQJYhGmLCgsHCAkEAwYF
AgoIFQUBAwIICQoDFgECAAoJEBRcXsmfYJlD0jcAnRRz9CKzrRa+KpOd1q9m6UiS
2NyIAJ4oLt1VOPI56ECweUwcqVQyyAnUyg==
=53pm
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.63

mQGiBFiEgIMRBADRQztFDTN7HxCEqzkVr5QSt1Zn+w0m1Q/GYyRRBupxU1bbMHLy
lzKBGdYyU4G+P4HmhBOmFGeXaqmpIpnfaAijqP9sxjY+pYi4255WouD3it2ECtwz
bev4OytzKgJD2wVuuoNMKVNbdBA1X1Lfivsn9nzD6WLFuL6esa6LSWPqqwCghIj6
iNbncjL9doaajnmOAL7a0gMEAMnrvu9J5IbXLSlgo+wzn9OpOR0QjmqFf+wtT6iH
bB5XIrOxFfYNyEDjIfbh3NGXtAm77y77J++W1hygvyZAfiAU0zUU+y0kpkLhMAAy
KniSYo2rE38N4AE1ziVdwqaZ27X4LxGgwuXOgnDCNf8m6OCrfB+TzsLD12srx9pN
jKMjA/9TPuXkO6SS2nCg0Yi1Cy6H0apaQ3ULyyyP2r5ERfHtfl6Iloj+UyBnj0nD
BlgTmQMC1498jUX66OUh5MkVyWLEVa8E7xgoZsRDX+2cilXt1M2r4VPwueZLiwM+
42jJFdbKyJE+zR0jAYW8lO2Xeh0VnH8Src3rCKId9Uur18QOXrQVUGF1bCA8cGF1
bEBlbWFpbC5jb20+iF4EExECAB4FAliEgIMKCwcICQQDBgUCCggVBQEDAggJCgMW
AQIACgkQ5wGWCZzxMxHLHgCfXa08yd1zJHm/N9AiVHXXC2PCRx4An36Cn14C72iZ
3SIBV9X2BbF0lD9IuQGMBFiEgIMQBACiFNi+9dXeOhMiTdYUjETtvtNlnXt+t2Pb
cCzQm/w5Ix42ByK2PRMi7sKtvIzTyY/eDcqt9skHBf/yU7qLrmIiCFUp/At7RpTE
p3ze2nRwE77wIgS6jjDtGd8xjJ8aop7FLeU0PtP8u9B79xa1BMBW71MXt1cZTc5u
q5BHsW5dSwP+Pc9xXIoWgC2w5tBPxtVMkzvS5j4UBT8PHgJFvpEc11BMksRK5juQ
qcjY1c4h6o4Bzu1SBWbP7S/avw8gQwN2s2dkErwKUB3SgrtXa1Rkkuod8x8YvOJF
hbQjnzskd3v+8W1HUGWsd5tmXxSIK1wwNbRYkuElx187fOxtrcfX4nAD/2byprWt
THIhgBXsoeAjTiZi+7Qie+nqBfQCSXD96qU348PLiGqOzfocTtPfw7yw43VrHOFe
IB5LbS7h0gY/PiTmdLDf65OSbURWAv6kFa/QX711N95vRsdp3lT5HfdiKdS38DwJ
T+PYWpMkvvnX3SJkcmeKtTUMecVIkDC3fzwciF4EGBECAB4FAliEgIMKCwcICQQD
BgUCCggVBQEDAggJCgMWAQIACgkQ5wGWCZzxMxH2QACdER6bpmMgAOu88S3rCQml
HK/99NcAn0Nbj+Hmb7mNVp72PaYbRKNCXd+J
=VAIT
-----END PGP PUBLIC KEY BLOCK-----

```

**Closed by skarpushin** 2019-09-22 19:35 UTC
Labels: feature request
